Repository make-a-good-soup/fugle-realtime-swift, pull requests merged in 2022-12, with the labels that each got.

#14 [add] Github Action
  .github/workflows/ci.yml
  README.md
Labels: test

#15 [Added] 新增 WebSocket 支援
  Examples/Realtime Demo/Realtime Demo/ContentView.swift
  Sources/fugle-realtime-swift/Models/Info.swift
  Sources/fugle-realtime-swift/Models/Intraday.swift
  Sources/fugle-realtime-swift/Models/Meta.swift
  Sources/fugle-realtime-swift/URLSessionWebSocketTask+Extension.swift
  Sources/fugle-realtime-swift/WebSocketRouter.swift
  Sources/fugle-realtime-swift/WebSocketStream.swift
Labels: feature

#19 [Changed] 新增 HTTPClient
  Examples/Realtime Demo/Realtime Demo/ContentView.swift
  Sources/fugle-realtime-swift/FugleHttpLoader.swift
  Sources/fugle-realtime-swift/HTTPClient/HTTPClient.swift
  Sources/fugle-realtime-swift/HTTPClient/URLSessionHTTPClient.swift
  Sources/fugle-realtime-swift/Router/APIRouter.swift
  Sources/fugle-realtime-swift/Router/IntradayRouter.swift
  Sources/fugle-realtime-swift/WebSocket/URLSessionWebSocketTask+Extension.swift
  Sources/fugle-realtime-swift/WebSocket/WebSocketRouter.swift
  Sources/fugle-realtime-swift/WebSocket/WebSocketStream.swift
  Tests/fugle-realtime-swiftTests/HTTPClient/Helpers/URLProtocolStub.swift
  Tests/fugle-realtime-swiftTests/HTTPClient/Helpers/XCTestCase+Extension.swift
  Tests/fugle-realtime-swiftTests/HTTPClient/URLSessionHTTPClientTests.swift
Labels: enhancement
